config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "pins#index"
    end
    unauthenticated :user do
      root to: "devise/sessions#new"
    end
  end

  resources :pins, except: [:edit, :update, :new] do
    member do
      put 'like', to: 'pins#upvote'
    end
  end
  post 'add_pin', to: 'pins#add_pin'
  get 'boards/:id/pin/new', to: 'pins#new', as: :new_pin

  resources :boards

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :pins, dependent: :destroy
  validates :name, presence: true
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :board
  validates :title, presence: true
  # validates :url, format: {with: /\.(png|jpg|gif)\Z/i}, :allow_blank => true
  has_attached_file :image #, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def data_from_url(url)
    object = LinkThumbnailer.generate(url)
    self.title = object.title
    self.description = object.description
    self.image = URI.parse(object.images.first.src.to_s).open
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pins
  has_many :boards, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_pin, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @boards = current_user.boards.order("created_at DESC")
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: "Successfully created new Board"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @board.update(board_params)
      redirect_to board_path(@board), notice: "Successfully updated your Board"
    else
      render 'edit'
    end
  end

  def show
    @pins = @board.pins.order("created_at DESC")
    @my_boards = current_user.boards
  end

  def destroy
    @board.destroy
    redirect_to root_path
  end

  private
    def set_pin
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name)
    end

    def require_same_user
      if current_user != @board.user
        redirect_to root_path
      end
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:edit, :update, :show, :destroy, :upvote]
  before_action :authenticate_user!
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :only_image_or_url, only: [:create]

  def index
    @pins = Pin.all.order("created_at DESC")
    @my_boards = current_user.boards
  end

  def new
    @board = params[:id]
    # if Board.find(@board).nil?
    @pin = current_user.pins.build
    # else
      # redirect_to root_path, notice: "Error occured while creating Pin"
    # end
  end

  def create
    # render plain: params.inspect
    @pin = current_user.pins.build(pin_params)
    if !params[:pin][:url].empty?
        @pin.data_from_url(@pin.url) 
    end
    if @pin.save
      redirect_to pin_path(@pin), notice: "Successfully created new Pin"
    else
      redirect_to new_pin_path(params[:pin][:board_id]), :params => params, :flash => { :error => @pin.errors.full_messages.join(' | ') }
    end
  end

  def edit
    @board = @pin.board.id
  end

  def update
    if @pin.update(pin_params)
      redirect_to pin_path(@pin), notice: "Successfully updated your Pin"
    else
      render 'edit'
    end
  end

  def show
    @my_boards = current_user.boards
  end

  def upvote
    @pin.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def add_pin
    # render plain: params.inspect
    pin = Pin.find(params[:pin_id])
    @new_pin = Pin.new
    @new_pin.title = params[:title]
    @new_pin.description = params[:description]
    @new_pin.image = pin.image
    @new_pin.url = pin.url
    @new_pin.user = current_user
    @new_pin.board_id = params[:board_id].to_i
    # render plain: @new_pin.inspect
    if @new_pin.save
      redirect_back fallback_location: root_path, notice: "Successfully added Pin"
    else
      redirect_back fallback_location: root_path, notice: "Problem encountered while adding Pin"
    end
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:title, :description, :image, :url, :board_id)
    end

    def require_same_user
      if current_user != @pin.user
        redirect_to root_path
      end
    end
    def only_image_or_url
      if params[:pin].has_key? :image
        if (params[:pin][:url].empty? && params[:pin][:image].nil?) || (!params[:pin][:url].empty? && !params[:pin][:image].nil?)
          # redirect_to root_path, notice: "Error: "
          redirect_back fallback_location: root_path, notice: "Error: Fill only one of the following: Image URL/Image Upload"
        end
      else
        if params[:pin][:url].empty?
          redirect_back fallback_location: root_path, notice: "Error: Fill only one of the following: Image URL/Image Upload" 
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/boards/_form.html.erb

    <%= simple_form_for @board, html: {multipart: true} do |f| %>
      
      <%= render 'shared/errors', obj: @board %>

      <div class="form-group">
        <%= f.input :name, input_html: { class: 'form-control' } %>
      </div>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>

app/views/boards/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 align="center">Edit Board</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/boards/index.html.erb

<div class="transitions-enabled" id="pins">
  <% @boards.each do |board| %>
    <div class="box panel panel-default">
      <div class="panel-header board">
        <h2><%= link_to board.name, board_path(board) %></h2>
      </div>
      <div class="panel-body">
        <p class="user">Created <%= time_ago_in_words board.created_at %> ago</p>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 align="center">Create Board</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div id="pin_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
      </div>
      <div class="panel-body">
        <h2><%= @board.name %></h2>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <% if user_signed_in? && current_user == @board.user %>
              <%= link_to "New Pin", new_pin_path(@board), class: "btn btn-default" %>
            <% end %>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <% if user_signed_in? && current_user == @board.user %>
                <%= link_to "Edit", edit_board_path(@board), class: "btn btn-primary" %>
                <%= link_to "Delete", board_path(@board), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="transitions-enabled" id="pins">
    <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        <%= link_to image_tag(pin.image.url), pin %>
        <div class="panel-body">
          <h2><%= link_to pin.title, pin_path(pin) %></h2>  
          <div class="row">
            <div class="col-md-10">
              <p class="user">Submitted by: <%= pin.user.email %></p>
              <p class="time">Created <%= time_ago_in_words pin.created_at %> ago</p>
            </div>
            <div class="col-md-2">
              <div class="btn-group pull-right">
                <% if user_signed_in? && current_user != pin.user %>
                  <%= link_to '#', class: "btn btn-default btn-xs", 'data-toggle' => "modal", 'data-target' => "#myModal", 'data-id' => pin.id, 'id' => 'add_pin_btn' do %>
                    <span class="glyphicon glyphicon-pushpin"></span>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render 'pins/modal' %>

app/views/layouts/_messages.html.erb
<!-- <div class="row"> -->
  <!-- <div class="col-xs-10 col-xs-offset-1"> -->
    <%# flash.each do |name, msg| %>
      <!-- <div class="alert alert-<%#= "#{name}" %> alert-dismissible" role="alert"> -->
        <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"> -->
          <!-- <span aria-hidden="true">&times;</span> -->
        <!-- </button> -->
       <!-- <strong><%#= msg %></strong> -->
      <!-- </div> -->
    <%# end %>
  <!-- </div> -->
<!-- </div> -->

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "PinApp", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Boards <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'My Boards', boards_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "New Board", new_board_path %></li>
          </ul>
        </li>
        <li><%= link_to "My Account", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pins/_form.html.erb

    <%= simple_form_for @pin, html: {multipart: true} do |f| %>
      
      <%= render 'shared/errors', obj: @pin %>

      <div class="form-group">
        <%= f.input :image, input_html: { class: 'form-control' } %>
      </div>
      <h3 align="center">OR</h3>
      <div class="form-group">
        <%= f.input :url, input_html: { class: 'form-control', type: 'url', pattern: "^(https?://)?([a-zA-Z0-9]([a-zA-ZäöüÄÖÜ0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,6}$" } %>
      </div><hr>
      <div class="form-group">
        <%= f.input :title, input_html: { class: 'form-control' } %>
      </div>
      <div class="form-group">
        <%= f.input :description, input_html: { class: 'form-control' } %>
      </div>
        <%= f.hidden_field :board_id, :value => @board %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>

app/views/pins/_modal.html.erb
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Pin</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-12">
            <%= form_tag add_pin_path, method: :post, class: "form-horizontal", role: "form" do %>
              <div class="form-group">
                <div class="col-xs-2 control-label">
                  <%= label_tag(:title, "Title:") %>
                </div>
                <div class="col-xs-10">
                  <%= text_field_tag(:title,"", class: "form-control", placeholder: "Enter title", autofocus: true) %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-xs-2 control-label">
                  <%= label_tag(:description, "Description:") %>
                </div>
                <div class="col-xs-10">
                  <%= text_field_tag(:description,"", class: "form-control", placeholder: "Enter description") %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-xs-2 control-label">
                  <%= label_tag(:board, "Board:") %>
                </div>
                <div class="col-xs-10">
                  <%= select_tag :board_id, options_from_collection_for_select(@my_boards, "id", "name"), class: "form-control" %>  
                </div>
              </div>
              <%= hidden_field_tag :pin_id %>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                <%= submit_tag("Add Pin", class: "btn btn-primary") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">
  $(document).on("click", "#add_pin_btn", function () {
     var myPinId = $(this).data('id');
     $(".modal-body #pin_id").val( myPinId );
  });
</script>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 align="center">Edit Pin</h1>
      </div>
      <div class="panel-body">
        <div align="center" id="pin_edit"><%= image_tag @pin.image.url %></div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/index.html.erb

<div class="transitions-enabled" id="pins">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url), pin %>
      <div class="panel-body">
        <h2><%= link_to pin.title, pin_path(pin) %></h2>  
        <p class="user">Submitted by: <%= pin.user.email %></p>
        <p class="time">Created <%= time_ago_in_words pin.created_at %> ago</p>
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2">
            <h5><strong>Board: <%= link_to pin.board.name, board_path(pin.board) %></strong></h5>
          </div>
          <div class="col-xs-2">
            <div class="btn-group pull-right">
              <% if user_signed_in? && current_user != pin.user %>
                <%= link_to '#', class: "btn btn-default btn-xs", 'data-toggle' => "modal", 'data-target' => "#myModal", 'data-id' => pin.id, 'id' => 'add_pin_btn' do %>
                  <span class="glyphicon glyphicon-pushpin"></span>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= render 'modal' %>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 align="center">Create Pin</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div id="pin_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url %>      
      </div>
      <div class="panel-body">
        <h1><%= @pin.title %></h1>
        <p class="description"><%= @pin.description %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">Submitted By: <%= @pin.user.email %></p>
          </div>
          <div class="col-md-6">
            <div class="pull-right">
              <% if user_signed_in? && current_user != @pin.user %>
                <%= link_to '#', class: "btn btn-default", 'data-toggle' => "modal", 'data-target' => "#myModal", 'data-id' => @pin.id, 'id' => 'add_pin_btn' do %>
                  <span class="glyphicon glyphicon-pushpin"></span>
                <% end %>
              <% end %>
              <div class="btn-group">
                <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
                  <span class="glyphicon glyphicon-heart"> <%= @pin.get_upvotes.size %></span>
                <% end %>
                <% if user_signed_in? && current_user == @pin.user %>
                  <%#= link_to "Edit", edit_pin_path(@pin, :board => @pin.board), class: "btn btn-default" %>
                  <%= link_to "Delete", pin_path(@pin), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'modal' %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(obj.errors.count, "error") %> found in the form:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>